[package]
name = "cryptopals"
version = "0.1.0"
authors = ["chris <chris.j.bury@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.3.2"
block-modes = "0.3.3"